;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Jan 16 2023
; Processor: PIC16F84A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f84a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
parseResult     equ 0x30
ZERO equ 0x0
ONE equ 0x1
TWO equ 0x2
THREE equ 0x3
FOUR equ 0x4
FIVE equ 0x5
SIX equ 0x6
SEVEN equ 0x7
EIGHT equ 0x8
NINE equ 0x9
ASTERISK equ 0xA
SQUARE equ 0xB
delay1 equ 0x31
delay2 equ 0x32

org 0x2100 ; EEPROM offset for pic16f84a
de 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xA, 0xB ; tones bytes for every digit
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

DELAY:
	BCF STATUS, RP0 ; Bank 0
	MOVLW 0xC4
	MOVWF delay1
	MOVLW 0xC4
	MOVWF delay2
DELAY_LOOP_START:
	DECFSZ delay1, 1
	GOTO DELAY_LOOP_ADDITIONAL
	DECFSZ delay2, 1	
DELAY_LOOP_ADDITIONAL:
	GOTO DELAY_LOOP_START
	RETURN

PARSE_CHARACTER_W:     
     MOVLW 0x20
     MOVWF parseResult

     MOVF PORTB, 0
     ANDLW b'11111000'
     IORLW b'00000011'
     MOVWF PORTB
     
     BTFSS PORTB, 4
     MOVLW 1
     BTFSS PORTB, 4
     MOVWF parseResult
     BTFSS PORTB, 5
     MOVLW 4
     BTFSS PORTB, 5
     MOVWF parseResult
     BTFSS PORTB, 6
     MOVLW 7
     BTFSS PORTB, 6
     MOVWF parseResult
     BTFSS PORTB, 7
     MOVLW 0x0A
     BTFSS PORTB, 7
     MOVWF parseResult
     
     MOVF PORTB, 0
     ANDLW b'11111000'
     IORLW b'00000101'
     MOVWF PORTB

     BTFSS PORTB, 4
     MOVLW 2
     BTFSS PORTB, 4
     MOVWF parseResult
     BTFSS PORTB, 5
     MOVLW 5
     BTFSS PORTB, 5
     MOVWF parseResult
     BTFSS PORTB, 6
     MOVLW 8
     BTFSS PORTB, 6
     MOVWF parseResult
     BTFSS PORTB, 7
     MOVLW 0
     BTFSS PORTB, 7
     MOVWF parseResult
     
     MOVF PORTB, 0
     ANDLW b'11111000'
     IORLW b'00000110'
     MOVWF PORTB

     BTFSS PORTB, 4
     MOVLW 3
     BTFSS PORTB, 4
     MOVWF parseResult
     BTFSS PORTB, 5
     MOVLW 6
     BTFSS PORTB, 5
     MOVWF parseResult
     BTFSS PORTB, 6
     MOVLW 9
     BTFSS PORTB, 6
     MOVWF parseResult
     BTFSS PORTB, 7
     MOVLW 0x0B
     BTFSS PORTB, 7
     MOVWF parseResult
     
    MOVF PORTB, 0
    ANDLW b'11111000'
    MOVWF PORTB
    RETURN

HANDLE_BUTTON_CLICK:
    MOVF parseResult, 0
    MOVWF EEADR
    BSF STATUS, RP0
    BSF EECON1, RD
    BCF STATUS, RP0
    MOVF EEDATA, 0
    MOVWF PORTA ; send byte from EEDATA to sounder
    RETURN

PGM   code
Start
     BCF STATUS, RP0 ; Bank 0
     CLRF PORTB; Initializing PORTB
     CLRF PORTA ; Initializing PORTA
     BSF STATUS, RP0 ; Bank 1
     MOVLW b'11110000' ; bit value for TRISB state
     MOVWF TRISB
     CLRF TRISA
     BCF OPTION_REG, 7 
     BCF STATUS, RP0 ; Bank 0
Loop  
      goto  Loop
      CALL PARSE_CHARACTER_W
      MOVF parseResult, 0
      SUBLW 0x20
      BTFSS STATUS, Z
      CALL HANDLE_BUTTON_CLICK
;====================================================================
      END
