;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Jan 16 2023
; Processor: PIC16F84A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f84a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
BTN        equ 0
LED         equ 5
counter equ 0x32
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start
   
COUNTER_TO_PORTB:
    BTFSS counter, 0
    BCF PORTB, 4
    BTFSC counter, 0
    BSF PORTB, 4
    
    BTFSS counter, 1
    BCF PORTB, 3
    BTFSC counter, 1
    BSF PORTB, 3
    
    BTFSS counter, 2
    BCF PORTB, 2
    BTFSC counter, 2
    BSF PORTB, 2
    
    BTFSS counter, 3
    BCF PORTB, 1
    BTFSC counter, 3
    BSF PORTB, 1   
    
    RETURN
   
HANDLE_BUTTON_CLICK:
    INCF counter, 1
    CALL COUNTER_TO_PORTB
    BTFSS PORTB, LED
    GOTO TURNON
    BTFSC PORTB, LED
    GOTO TURNOF
TURNON:
    BSF PORTB, LED
    RETURN
TURNOF:
    BCF PORTB, LED
    RETURN


;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      BCF STATUS, RP0
      CLRF PORTA
      CLRF PORTB
      BSF STATUS, RP0
      CLRF TRISA
      CLRF TRISB
      BSF TRISB, BTN
      BCF STATUS, RP0
      CLRF counter
Loop  
WAIT_FOR_FIRST_PRESS:
    BTFSC PORTB, BTN
    GOTO WAIT_FOR_FIRST_PRESS
    CALL HANDLE_BUTTON_CLICK
WAIT_FOR_FIRST_UNPRESS:
    BTFSS PORTB, BTN
    GOTO WAIT_FOR_FIRST_UNPRESS

      goto  Loop

;====================================================================
      END