;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Jan 16 2023
; Processor: PIC16F84A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f84a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
BTN1        equ 0
BTN2        equ 1
LED         equ 0
delay1 	equ 0x30
delay2	equ 0x31
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start
   

DELAY:
	BCF STATUS, RP0 ; Bank 0
	MOVLW 0xC4
	MOVWF delay1
	MOVLW 0xC4
	MOVWF delay2
DELAY_LOOP_START:
	DECFSZ delay1, 1
	GOTO DELAY_LOOP_ADDITIONAL
	DECFSZ delay2, 1	
DELAY_LOOP_ADDITIONAL:
	GOTO DELAY_LOOP_START
	RETURN
   
 TOGGLE:
    BTFSS PORTA, LED
    GOTO TURNON
    BTFSC PORTA, LED
    GOTO TURNOF
TURNON:
    BSF PORTA, LED
    RETURN
TURNOF:
    BCF PORTA, LED
    RETURN

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      BCF STATUS, RP0
      CLRF PORTA
      CLRF PORTB
      BSF STATUS, RP0
      CLRF TRISA
      CLRF TRISB
      BSF TRISB, BTN1
      BSF TRISB, BTN2
      BCF STATUS, RP1
Loop  
WAIT_FOR_FIRST_PRESS:
    CALL TOGGLE
    CALL DELAY
    BTFSC PORTB, BTN1
    GOTO WAIT_FOR_SECOND_PRESS
    CALL TOGGLE
    GOTO WAIT_FOR_FIRST_UNPRESS
WAIT_FOR_SECOND_PRESS:
    BTFSC PORTB, BTN2
    GOTO WAIT_FOR_FIRST_PRESS
    CALL TOGGLE
    GOTO WAIT_FOR_SECOND_UNPRESS
WAIT_FOR_FIRST_UNPRESS:
    BTFSS PORTB, BTN1
    GOTO WAIT_FOR_FIRST_PRESS
WAIT_FOR_SECOND_UNPRESS:
    BTFSS PORTB, BTN2
    GOTO WAIT_FOR_FIRST_PRESS

      goto  Loop

;====================================================================
      END
