;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Jan 9 2023
; Processor: PIC16F84A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f84a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
delay1 		equ 	0x30
delay2 		equ 	0x31
index		equ   0x32

ZERO	equ   0x33
ONE	equ	0x34
TWO equ 0x35
THREE equ 0x36
FOUR equ 0x37
FIVE equ 0x38
SIX equ 0x39
SEVEN equ 0x3A
EIGHT equ 0x3B
NINE equ 0x3C

digit0	equ 0x3D
digit1	equ	0x3E
digit2	equ	0x3F
digit3	equ	0x40
digit4	equ	0x41
digit5	equ	0x42
bitsForDigits equ 0x43
portbMask equ 0x44

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start
      
CLEAR_DIGITS:
   CLRF digit0
   CLRF digit1
   CLRF digit2
   CLRF digit3
   CLRF digit4
   CLRF digit5
   RETURN

;b1 b0 a4 a3 a2 a1 a0 ?
;g   f    e   d   c   b  a  0
;1  0    0   0   0   0  0  0
INIT_MASK_ARRAY:
   MOVLW b'10000000'
   MOVWF ZERO
   MOVLW b'11110010'
   MOVWF ONE
   MOVLW b'01001000'
   MOVWF TWO
   MOVLW b'01100000'
   MOVWF THREE
   MOVLW b'00110010'
   MOVWF FOUR
   MOVLW b'00100100'
   MOVWF FIVE
   MOVLW b'00000100'
   MOVWF SIX
   MOVLW b'11110000'
   MOVWF SEVEN
   MOVLW b'00000000'
   MOVWF EIGHT
   MOVLW b'00100000'
   MOVWF NINE
   RETURN
   
SET_BITS_FOR_DIGIT:
     MOVLW ZERO
     ADDWF INDF, 0
     MOVWF FSR ; now indf reference to the required mask
     
     ; set bits for ports
     MOVF INDF, 0
     MOVWF bitsForDigits
     CLRF PORTA
     BTFSC bitsForDigits, 1
     BSF PORTA, 0
     BTFSC bitsForDigits, 2
     BSF PORTA, 1
     BTFSC bitsForDigits, 3
     BSF PORTA, 2
     BTFSC bitsForDigits, 4
     BSF PORTA, 3
     BTFSC bitsForDigits, 5
     BSF PORTA, 4
     CLRF PORTB
     BTFSC bitsForDigits, 6
     BSF PORTB, 0
     BTFSC bitsForDigits, 7
     BSF PORTB, 1
     RETURN

PRINT_DIGITS:
     MOVLW b'00000100'
     MOVWF portbMask
     BCF STATUS, C
     
     CLRF PORTB
     MOVLW digit0
     MOVWF FSR
     CALL SET_BITS_FOR_DIGIT
     BSF PORTB, 2
     CALL DELAY

     CLRF PORTB
     MOVLW digit1
     MOVWF FSR
     CALL SET_BITS_FOR_DIGIT
     BSF PORTB, 3
     CALL DELAY     

     CLRF PORTB
     MOVLW digit2
     MOVWF FSR
     CALL SET_BITS_FOR_DIGIT
     BSF PORTB, 4
     CALL DELAY     
     
     CLRF PORTB
     MOVLW digit3
     MOVWF FSR
     CALL SET_BITS_FOR_DIGIT
     BSF PORTB, 5
     CALL DELAY     
     
     CLRF PORTB
     MOVLW digit4
     MOVWF FSR
     CALL SET_BITS_FOR_DIGIT
     BSF PORTB, 6
     CALL DELAY     
     
     CLRF PORTB
     MOVLW digit5
     MOVWF FSR
     CALL SET_BITS_FOR_DIGIT
     BSF PORTB, 7
     CALL DELAY     
     
     RETURN

INCREMENT_DIGITS:
    INCF digit5, 1
    MOVLW 0xA
    SUBWF digit5, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit5
    INCF digit4, 1
    MOVLW 0x7
    SUBWF digit4, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit4
    INCF digit3, 1
    MOVLW 0xA
    SUBWF digit3, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit3
    INCF digit2, 1
    MOVLW 0x7
    SUBWF digit2, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit2
    INCF digit1, 1
    MOVLW 0xA
    SUBWF digit1, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit1
    INCF digit0, 1
    MOVLW 0x7
    SUBWF digit0, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit0
    
    RETURN
      
DELAY:
	BCF STATUS, RP0 ; Bank 0
	MOVLW 0x4E
	MOVWF delay1
	MOVLW 0x20
	MOVWF delay2
DELAY_LOOP_START:
	DECFSZ delay1, 1
	GOTO DELAY_LOOP_ADDITIONAL
	DECFSZ delay2, 1
DELAY_LOOP_ADDITIONAL:
	GOTO DELAY_LOOP_START
	RETURN
;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      BSF STATUS, RP0
      CLRF TRISB
      CLRF TRISA
      BCF STATUS, RP0
      CLRF PORTB
      CLRF PORTA
      CALL CLEAR_DIGITS
      CALL INIT_MASK_ARRAY
Loop   
      CALL PRINT_DIGITS
      CALL INCREMENT_DIGITS
      CALL DELAY
      goto  Loop

;====================================================================
      END
