;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Jan 9 2023
; Processor: PIC16F84A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f84a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
delay1 		equ 	0x30
delay2 		equ 	0x31
index		equ   0x32

ZERO	equ   0x33
ONE	equ	0x34
TWO equ 0x35
THREE equ 0x36
FOUR equ 0x37
FIVE equ 0x38
SIX equ 0x39
SEVEN equ 0x3A
EIGHT equ 0x3B
NINE equ 0x3C

digit0	equ 0x3D
digit1	equ	0x3E
digit2	equ	0x3F
digit3	equ	0x40

isCounting equ 0x41
interval equ 0x42

TIMER0 equ b'00000001'
TIMER1 equ b'00000010'
TIMER2 equ b'00000100'
TIMER3 equ b'00011000'
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start
      
CLEAR_DIGITS:
   CLRF digit0
   CLRF digit1
   CLRF digit2
   CLRF digit3
   RETURN


INIT_MASK_ARRAY:
   MOVLW b'10000000'
   MOVWF ZERO
   MOVLW b'11110010'
   MOVWF ONE
   MOVLW b'01001000'
   MOVWF TWO
   MOVLW b'01100000'
   MOVWF THREE
   MOVLW b'00110010'
   MOVWF FOUR
   MOVLW b'00100100'
   MOVWF FIVE
   MOVLW b'00000100'
   MOVWF SIX
   MOVLW b'11110000'
   MOVWF SEVEN
   MOVLW b'00000000'
   MOVWF EIGHT
   MOVLW b'00100000'
   MOVWF NINE
   RETURN

PRINT_DIGITS:
     MOVLW ZERO
     ADDWF digit0, 0
     MOVWF FSR
     MOVF INDF, 0
     MOVWF PORTB
     MOVLW TIMER0
     MOVWF PORTA
     CALL DELAY


     MOVLW ZERO
     ADDWF digit1, 0
     MOVWF FSR
     MOVF INDF, 0
     MOVWF PORTB
     MOVLW TIMER1
     MOVWF PORTA
     CALL DELAY

     MOVLW ZERO
     ADDWF digit2, 0
     MOVWF FSR
     MOVF INDF, 0
     MOVWF PORTB
     MOVLW TIMER2
     MOVWF PORTA
     CALL DELAY

     MOVLW ZERO
     ADDWF digit3, 0
     MOVWF FSR
     MOVF INDF, 0
     MOVWF PORTB
     MOVLW TIMER3
     MOVWF PORTA
     CALL DELAY
     RETURN

INCREMENT_DIGITS:
    INCF digit3, 1
    MOVLW 0xA
    SUBWF digit3, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit3
    INCF digit2, 1
    MOVLW 0xA
    SUBWF digit2, 0
    BTFSS STATUS, 2
    RETURN
    
    CLRF digit2
    INCF digit1, 1
    MOVLW 0xA
    SUBWF digit1, 0
    BTFSS STATUS, 2
    RETURN
    
     CLRF digit1
    INCF digit0, 1
    MOVLW 0xA
    SUBWF digit0, 0
    BTFSS STATUS, 2
    RETURN
    
    RETURN

COUNTING_STEP:
    CALL INCREMENT_DIGITS
    RETURN
    
 WAIT_FOR_UNPRESS:
 WAIT_FOR_UNPRESS_WAIT:
    BTFSS PORTB, 0
    GOTO WAIT_FOR_UNPRESS_WAIT
    RETURN

START_COUNTING:
    BTFSC isCounting, 0
    RETURN
    BSF isCounting, 0
    CALL CLEAR_DIGITS
    CALL WAIT_FOR_UNPRESS
   
    RETURN

STOP_COUNTING:
    BTFSS isCounting, 0
    RETURN
    BCF isCounting, 0
    CALL WAIT_FOR_UNPRESS
    RETURN

HANDLE_BUTTON_CLICK:
    BTFSS PORTB, 0
    CALL START_COUNTING
    BTFSS PORTB, 0
    CALL STOP_COUNTING
    RETURN
      
DELAY:
	BCF STATUS, RP0 ; Bank 0
	MOVLW 0x4E
	MOVWF delay1
	MOVLW 0x10
	MOVWF delay2
DELAY_LOOP_START:
        CALL HANDLE_BUTTON_CLICK
	DECFSZ delay1, 1
	GOTO DELAY_LOOP_ADDITIONAL
	DECFSZ delay2, 1
DELAY_LOOP_ADDITIONAL:
	GOTO DELAY_LOOP_START
	RETURN
;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      BCF STATUS, RP0
      CLRF PORTB
      CLRF PORTA
      BSF STATUS, RP0
      CLRF TRISB
      BSF TRISB, 0
      CLRF TRISA
      BCF STATUS, RP0
      
      CALL CLEAR_DIGITS
      CALL INIT_MASK_ARRAY
Loop   
      CALL PRINT_DIGITS
      BTFSC isCounting, 0
      CALL COUNTING_STEP
      goto  Loop

;====================================================================
      END
