;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Jan 9 2023
; Processor: PIC16F84A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f84a.inc                ; Include register definition file

delay1 equ 0x30
delay2 equ 0x31

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start
   

 DELAY_SMALL:
	BCF STATUS, RP0 ; Bank 0
	MOVLW 0x4E
	MOVWF delay1
	MOVLW 0x20
	MOVWF delay2
DELAY_SMALL_DELAY_LOOP_START:
	DECFSZ delay1, 1
	GOTO DELAY_SMALL_DELAY_LOOP_ADDITIONAL
	DECFSZ delay2, 1
DELAY_SMALL_DELAY_LOOP_ADDITIONAL:
	GOTO DELAY_SMALL_DELAY_LOOP_START
	RETURN
   
DELAY:
	BCF STATUS, RP0 ; Bank 0
	MOVLW 0x4E
	MOVWF delay1
	MOVLW 0xC4
	MOVWF delay2
DELAY_LOOP_START:
	DECFSZ delay1, 1
	GOTO DELAY_LOOP_ADDITIONAL
	DECFSZ delay2, 1
DELAY_LOOP_ADDITIONAL:
	GOTO DELAY_LOOP_START
	RETURN
;====================================================================
; CODE SEGMENT
;====================================================================

ITERATE_TRAFFIC:
   BCF STATUS, RP0
   ; all red
   MOVLW b'00000001'
   MOVWF PORTA
   MOVLW b'00100100'
   MOVWF PORTB
   CALL DELAY
   
   ; red with yellow 1 and 3, 2 is red
   MOVLW b'00000011'
   MOVWF PORTA
   MOVLW b'01100100'
   MOVWF PORTB
   CALL DELAY_SMALL
   
   ; green 1 and 3, 2 is red
   MOVLW b'00000100'
   MOVWF PORTA
   MOVLW b'10000100'
   MOVWF PORTB
   CALL DELAY
   CALL DELAY
   
   ; green 3, 1 is blinking, 2 is red 
   MOVLW b'00000000'
   MOVWF PORTA
   CALL DELAY_SMALL
   MOVLW b'00000100'
   MOVWF PORTA
   CALL DELAY_SMALL
   
   ; green 3, 1 is yellow, 2 is red
   MOVLW b'00000010'
   MOVWF PORTA
   MOVLW b'10000100'
   MOVWF PORTB
   CALL DELAY_SMALL
   
   ; green 3, 2 and 1 are red
   MOVLW b'00000001'
   MOVWF PORTA
   MOVLW b'10000100'
   MOVWF PORTB
   CALL DELAY
   CALL DELAY
   
   ; blink 3, 2 and 1 are red
   MOVLW b'00000100'
   MOVWF PORTB
   CALL DELAY_SMALL
   MOVLW b'10000100'
   MOVWF PORTB
   CALL DELAY_SMALL
   
   ; yellow 3, yellow and red 2, 1 is red
   MOVLW b'01001100'
   MOVWF PORTB
   CALL DELAY_SMALL
   
   ; red 3, green 2, 1 is red
   MOVLW b'00110000'
   MOVWF PORTB
   CALL DELAY
   CALL DELAY
   
   ;blink 2, 3 is red, 1 is red
   MOVLW b'00100000'
   MOVWF PORTB
   CALL DELAY_SMALL
   MOVLW b'00110000'
   MOVWF PORTB
   CALL DELAY_SMALL
   
   ; yellow 2, 3 is red, 1 is yellow with red
     MOVLW b'00000011'
     MOVWF PORTA
     MOVLW b'00101000'
     MOVWF PORTB
     CALL DELAY
     
     ; 2 and 3 are red, 1 is green
     MOVLW b'00000100'
     MOVWF PORTA
     MOVLW b'00100100'
     MOVWF PORTB
     CALL DELAY
     CALL DELAY
     
     ; blink 1, 2 and 3 are red
     MOVLW b'00000000'
     MOVWF PORTA
     CALL DELAY_SMALL
     MOVLW b'00000100'
     MOVWF PORTA
     CALL DELAY_SMALL
     
     ; 3 and 2 are red, 1 is yellow
     MOVLW b'00000010'
     MOVWF PORTA
     CALL DELAY
     ; with next iteration initial state are all red
   RETURN

PGM   code
Start
      BCF STATUS, RP0
      CLRF PORTB
      CLRF PORTA
      BSF STATUS, RP0
      CLRF TRISB
      BSF TRISB, 0
      CLRF TRISA
      BCF STATUS, RP0
      
Loop  
      CALL ITERATE_TRAFFIC
      goto  Loop

;====================================================================
      END
